<h1><img class="unit ugeb" src="img/x.gif"> Trapper</h1><img class="building g36" src="img/x.gif" alt="Trapper" title="Trapper" />The trapper protects your village with well hidden traps. This means that unwary enemies can be imprisoned and won't be able to harm your village anymore.
<br /><br />
One trap costs <img src="img/un/res/1.gif" width="18" height="12">20 | <img src="img/un/res/2.gif" width="18" height="12">30 | <img src="img/un/res/3.gif" width="18" height="12">10 | <img src="img/un/res/4.gif" width="18" height="12">20 | <img src="img/un/res/5.gif" width="18" height="12">0
<br /><br />
Troops cannot be freed with a raid. When the troops get freed with a successful normal attack, 1/3 of the traps are automatically repaired. If the owner of the traps release the captives all of the traps can be repaired. 
<br /><br />
Note that this building can only be constructed by <?php echo (defined("LANG") && LANG === "ar") ? "الغال" : "Gauls"; ?>.<p><b><?php echo (defined("LANG") && LANG === "ar") ? "التكاليف" : "Costs"; ?></b> <?php echo (defined("LANG") && LANG === "ar") ? "و" : "and"; ?> <b><?php echo (defined("LANG") && LANG === "ar") ? "وقت البناء" : "construction time"; ?></b> <?php echo (defined("LANG") && LANG === "ar") ? "للمستوى 1" : "for level 1"; ?>:<br /><?php echo (defined("LANG") && LANG === "ar") ? '<img class="r1" src="img/x.gif" alt="الخشب" title="الخشب" />' : '<img class="r1" src="img/x.gif" alt="Lumber" title="Lumber" />'; ?>100 | <?php echo (defined("LANG") && LANG === "ar") ? '<img class="r2" src="img/x.gif" alt="الطين" title="الطين" />' : '<img class="r2" src="img/x.gif" alt="Clay" title="Clay" />'; ?>100 | <?php echo (defined("LANG") && LANG === "ar") ? '<img class="r3" src="img/x.gif" alt="الحديد" title="الحديد" />' : '<img class="r3" src="img/x.gif" alt="Iron" title="Iron" />'; ?>100 | <?php echo (defined("LANG") && LANG === "ar") ? '<img class="r4" src="img/x.gif" alt="القمح" title="القمح" />' : '<img class="r4" src="img/x.gif" alt="Crop" title="Crop" />'; ?>100 | <?php echo (defined("LANG") && LANG === "ar") ? '<img class="r5" src="img/x.gif" alt="استهلاك القمح" title="استهلاك القمح" />' : '<img class="r5" src="img/x.gif" alt="Crop consumption" title="Crop consumption" />'; ?>4 | <span class="dur"><img class="clock" alt="duration" title="duration" src="img/x.gif" />0:33:20</span></p>
	<p><b><?php echo (defined("LANG") && LANG === "ar") ? "المتطلبات" : "Prerequisites"; ?></b><br /><a href="manual.php?typ=4&gid=16">Rally Point</a> <?php echo (defined("LANG") && LANG === "ar") ? "المستوى" : "Level"; ?> 1</p>
<map id="nav" name="nav">
    <area href="manual.php?typ=4&amp;gid=42" title="<?php echo (defined("LANG") && LANG === "ar") ? 'رجوع' : 'back'; ?>" coords="0,0,45,18" shape="rect" alt="" />
    <area href="manual.php?s=1" title="<?php echo (defined("LANG") && LANG === "ar") ? 'نظرة عامة' : 'Overview'; ?>" coords="46,0,70,18" shape="rect" alt="" />
    <area href="manual.php?typ=4&amp;gid=37" title="<?php echo (defined("LANG") && LANG === "ar") ? 'التالي' : 'forward'; ?>" coords="71,0,116,18" shape="rect" alt="" />
</map>
<img usemap="#nav" src="img/x.gif" class="navi" alt="" />